accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[

]

app_practice/urls.py
from django.contrib import admin
from django.urls import path, include
from app_practice import views

app_name = 'app_practice'

urlpatterns = [
    path('root/', views.root, name='root'),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views 

app_name = 'board'
urlpatterns = [
    # 게시판
    # Read (전체글)
    path('', views.index, name='b_index'),
    # Read (게시물 보기)
    path('<int:id>/', views.content, name='content'),
    # Create (게시물 등록)
    path('create/', views.create, name='create'),
    # Update (수정내용 등록)
    path('<int:id>/update/', views.update, name='update'),
    # Delete (게시물 삭제)
    path('<int:id>/delete/', views.delete, name='delete'),

    # 댓글
    # Create
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    # delete
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include
from app_practice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    # 게시판
    path('board/', include('board.urls')),
    # django 친해지기
    path('app_practice/', include('app_practice.urls')),
    # accounts
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

app_practice/models.py
from django.db import models

board/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Post(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.CharField(max_length=100)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

board/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

accounts/views.py
from django.shortcuts import render

# Create your views here.

app_practice/views.py
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'home.html')
    
def start(request):
    greeting = '안녕하세요'
    result = {
        'greeting': greeting,
    }
    return render(request, 'start.html', result)

def root(request): 
    input = request.GET.get('input')
    if input:
        rootnum = int(input) ** 0.5
        if rootnum == int(rootnum):
            rootnum = int(rootnum)
        result = {
            'input': input,
            'rootnum': rootnum,
        }
        return render(request, 'root.html', result)
    else:
        return render(request, 'root.html')

board/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm

# CRUD 구현 연습
# 게시판 전체페이지
def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,  
    }
    return render(request, 'board_index.html', context)
# 게시물 보기

def content(request, id):
    post = Post.objects.get(id=id)
    form = CommentForm()

    # comments = post.comment_set.all()
    context = {
        'post': post,
        'form': form,
        # 'comments': comments,
    }
    return render(request, 'content.html', context)

# 작성등록
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('board:content', id=post.id)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)
    
# 수정내용 등록
def update(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('board:content', id=post.id)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('board:b_index')

def comment_create(request, post_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post_id = post_id
        comment.save()
        return redirect('board:content', id=post_id)

def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return redirect('board:content', id=post_id)

app_practice/templates/home.html
{% extends 'base.html' %}

{% block body %}
{% load static %}
<div class="m-5">
<img src="{% static 'image/hodoo.jpg' %}" class="img-fluid" alt="hodoo">
</div>
{% endblock %}

app_practice/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Django연습페이지</h1>
    <a href="/board/"><h2>게시판</h2></a>
    <a href="/root/"><h2>제곱근계산기</h2></a>
</body>
</html>

app_practice/templates/index11.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Django연습페이지</h1>
    <a href="/board/"><h2>게시판</h2></a>
    <a href="/root/"><h2>제곱근계산기</h2></a>
</body>
</html>

app_practice/templates/root.html
{% extends 'base.html' %}
{% block body %}
    <h2><제곱근계산기></h2>
    <form action="">
        <label for="input" class="form-label" value = {{input}}>숫자입력</label>
        <input type="text" name="input" id="input" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" class="form-control">
        <input type="submit" value="calulate">
    </form>
    <label for="result" class="form-label">결과값</label>
    <input type="text" name="result" id="result" class="form-control" readonly value = {{rootnum}} >
{% endblock %}

app_practice/templates/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>인사합시다.</h1>
    <p>{{greeting}}</p>
</body>
</html>

board/templates/board_index.html
{% extends 'base.html' %}

{% block body %}
<div class="d-flex justify-content-end">
<a href="{% url 'board:create' %}" class="btn btn-light">게시물작성</a>
</div>
<table class="table mt-1">
    <thead class="table-primary">
        <tr>
            <th scope="col">#</th>
            <th scope="col">title</th>
        </tr>
    </thead>
    <tbody>
        {% for post in posts %}
        <tr>
            <td>{{ post.id }}</td>
            <td><a href="{% url 'board:content' id=post.id %}">{{ post.title }}</a></td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

board/templates/content.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <div class="d-inline align-self-center">
                # {{post.id}}
                {{post.title}}
            </div>
            <div class="d-inline">
                <a href="{% url 'board:b_index' %}" class="btn btn-secondary border">목록으로</a>
            </div>
        </div>
        <div class="card-body">
            {{ post.content }}
        </div>
        <div class="card-footer d-flex justify-content-between">
            <div class="d-inline align-self-center">
                {{ post.updated_at }}
            </div>
            <div class="d-inline">
                <a href="{% url 'board:update' id=post.id %}" class="btn btn-primary">수정</a>
                <a href="{% url 'board:delete' id=post.id %}" class="btn btn-danger">삭제</a>
            </div>
        </div>
    </div>

    <div class="card-header mt-4 border">댓글</div>
    
    <div>
    {% for comment in post.comment_set.all %}
        <div class="container d-flex justify-content-between">
            <span>{{ comment.content }}</span> 
            <a href="{% url 'board:comment_delete' post_id=post.id id=comment.id %}">delete</a>           
        </div>
        <div class="container">
            {{ comment.updated_at }}
        </div>
        <hr>
    {% endfor %}
    </div>
    <form action="{% url 'board:comment_create' post_id=post.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form show_label=False %}
        <input type="submit" value="작성" class="btn btn-primary">
    </form>
{% endblock %}

board/templates/edit.html
{% extends 'base.html' %}

{% block body %}
    <div class="d-flex justify-content-end">
        <a href="{% url 'board:content' id=post.id %}" class="btn btn-light">돌아가기</a>
    </div>
    <form action="{% url 'board:update' id=post.id %}">
       <div class="mb-3">
           <label for="title" class="form-label">제목</label>
           <input type="text" name="title" id="title" value={{post.title}} class="form-control">
       </div>
        <div class="mb-3">

            <label for="content" class="form-label">내용</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{ post.content }}</textarea>
        </div>
        <div class="d-flex justify-content-end">
            <input type="submit" value="수정" class="btn btn-primary">
            <a href="{% url 'board:delete' id=post.id %}" class="btn btn-danger">삭제</a>
        </div>
    </form>
{% endblock %}
  

board/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}

    <div class="d-flex justify-content-end">
        <a href="{% url 'board:b_index' %}" class="btn btn-light">돌아가기</a>
    </div>
    <form action="" method="POST" class="form">
        {% csrf_token %}

        {% bootstrap_form form %}
        {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
    </form>
{% endblock %}

templates/base.html
{% load bootstrap5 %}

{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dhyeon's Django</title>
  {% bootstrap_css %}
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Dhyeon's Django</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'board:b_index' %}">Board</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Practice
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'app_practice:root' %}">root calculator</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript %}

</body>

</html>